server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uduth_ambulance_service_db
    username: postgres
    password: a2144
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # Other options: create, create-drop, update, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true